### ISSUE TITLE
It is only reading one of the two GPUs

### ISSUE THREAD

**Issue by liesea** [CryptoGraphics/VerthashMiner#6]
Hello.

I am testing the miner on a notebook with GPU0 (intel UHD graphics) and GPU1 (NVIDIA GEforce MX130)
When I run the following BAT file:
VerthashMiner.exe -u ... -p ... -o stratum+tcp://vtc.suprnova.cc:1777 --verthash-data verthash.dat --all-cl-devices --all-cu-devices
pause;

I have only GPU0 working which is not what is needed.

However, If I remove --all-cl-devices  (as suggested on discord) i get the following error:
[2021-02-01 23:36:19] ERROR cu_device(0):Device not responding. error code: 702. Terminaning worker...

Could you advise please'
cheers

**Comment by CryptoGraphics** [comment]
It seems, that the default "WorkSize(131072)" parameter is probably too high for your GPU.
You can specify it individualy for each device.
Since you are using a command line configuration:
1. Open the **Windows Power Shell** in the same directory as **VerthashMiner.exe**
2. Use: `./VerthashMiner -l`
This will print all cappable devices as:
`Index: x. Name: Device name`
OpenCL and CUDA devices are listed separately.
In your case you want to select a CUDA device.
3. Instead of `--all-cu-devices` use `--cu-devices 0:w32768`
`0` is device index from the CUDA device list (`./VerthashMiner -l`)
`32768` is a custom `WorkSize` parameter.
4. So your BAT file will be:
`VerthashMiner.exe -u ... -p ... -o stratum+tcp://vtc.suprnova.cc:1777 --verthash-data verthash.dat --cu-devices 0:w32768`

**Comment by liesea** [comment]
it worked, but I am getting a low hashrate of 28.5k
I know I have an old GPU, but I thought it should perform  much better than the Intel GPU.
Is it possible that the worksize number is too small? can I increase to higher values and test if I get an error or not?
Thanks a lot

**Comment by CryptoGraphics** [comment]
Resolved with adaptive work size in v0.7.0.
