### ISSUE TITLE
Crashing rig

### ISSUE THREAD

**Issue by feaauser** [CryptoGraphics/VerthashMiner#7]
Hi. I've got two rigs with 7 GPUs each.
One has 6x Sapphire Pulse RX 570 4GB + 1 x Sapphire Nitro+ RX 580 4GB.
The other one has 7x Sapphire Nitro+ RX 580 4GB.
I've been mining ethash just fine and it ran for months without any crashes.
Yesterday I've tried to mine Vertcoin and the miner keeps crashing both rigs all the time, every few minutes.
I've installed AMD 19.7.5 drivers exclusively for this miner, newer drivers wouldn't let the miner use all GPUs.
The hashrate is great but it crashes all the time. 
I've tried different OC settings, even stock settings + stock BIOS. Even with stock gpu bios the system keeps crashing and restarting. 
Any ideas on what causes this?

**Comment by CryptoGraphics** [comment]
It is hard to say what exactly causes this issue.
Did you to try to select specific GPUs to isolate the problem?
Instead of using `--all-cl-devices` you can select (for example: GPUs 0,1,3 and set WorkSize 131072 for each of them)
`--cl-devices 0:w131072,1:w131072,3:w131072`

To get device list:
1. Open the **Windows Power Shell** in the same directory as **VerthashMiner.exe**
2. Use: `./VerthashMiner -l`
This will print all capable devices as:
`Index: x. Name: Device name`

**Comment by feaauser** [comment]
Yeah, I've tried that. Didn't make any difference.
I've ended up replacing mem timings on all my gpus to a new one. They're working mostly stable now. 
Not a miner issue.
The only thing that annoys me is that I have to restart the rig every time I play with any gpu setting or a single gpu fails.
