### ISSUE TITLE
 my  gh's are off the charts 

### ISSUE THREAD

**Issue by classiczero** [CryptoGraphics/VerthashMiner#8]
[debug.log](https://github.com/CryptoGraphics/VerthashMiner/files/5914617/debug.log)
![something feels wrong](https://user-images.githubusercontent.com/78448165/106666397-89a80100-6575-11eb-94a8-c1c6b04fd32d.PNG)
![why 2 0](https://user-images.githubusercontent.com/78448165/106666412-8dd41e80-6575-11eb-928c-5306f448aea8.PNG)

**Comment by gertjaap** [comment]
@CryptoGraphics : While this is an OneClickMiner debug log, it redirects VerthashMiner's stdout to the log. The log shows that VerthashMiner is reporting this hashrate:

```
INFO  cl_device(1): hashrate: 3876493.55 kH/s
```

@classiczero Can you please include more information about the exact type numbers your GPU has?

**Comment by steveocrypto** [comment]
@CryptoGraphics Can you confirm that the miner respects vardiff difficulty assignments from stratum?  It almost seems as if it's ignoring it and stratum protocol is thinking it's a much higher diff due to the adjustments.

Eg. (assuming no block found)

- Miner connects, diff assigned 1.
- After 1.5 min, stratum re-assigns 2.
- Miner continues to mine at 1, stratum thinks work received is 2.
- Shares are received multiplied as the diff 2 shares come in at the same speed.
- Vardiff re-assigns 4 since the speed hasn't been reduced.
- 1.5 min later, still receiving shares at 4 at the same speed, vardiff assign 8 now.
-  And so on..

Hope that makes sense.  After a stretch of no blocks (4+ min with a 2.5min block target), I've seen immense multiples of sharediffs and seemingly no frequency reduction in work being received.  The zero-reduction in shares being received at a much higher diff leads the pool stratum calculations to think it's a much, much higher hash rate than actual.

**Comment by classiczero** [comment]
so  what i am understanding is that i should be will receiving vtc all tho
i what it is saying is off the charts and i as for the gpu it is a AMD
Radeon (tm) RX 5600m

**Comment by IggyJ** [comment]
![Screenshot from 2021-02-09 18-22-31](https://user-images.githubusercontent.com/68810261/107409213-d6568380-6b03-11eb-854d-067a4bd2ca2f.png)
Hi, I'm experiencing the same issue. @classiczero did you manage to find a solution?
My card is a GTX 760 2GB

**Comment by classiczero** [comment]
no sorry i did not find a solution  and the vibe i was getting from the
admin or the people running it was there is no fix so i just
stoped mining if you found a solution ples let me know

**Comment by CryptoGraphics** [comment]
Resolved in v0.7.0
