### ISSUE TITLE
Miner is not listening to difficulty updates from the pool (vardiff)

### ISSUE THREAD

**Issue by ocminer** [CryptoGraphics/VerthashMiner#9]
The miner is always working with its initial diff but it's not updating it's job once it gets a difficulty update from the pool:

2021-02-03 13:37:20 [Pool]	[vtccoin] (Thread 5) Diff update to diff 1.6161616 workerName="vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn"
2021-02-03 13:37:22 [Pool]	[vtccoin] (Thread 5) Share accepted at diff 0.44444444/1.13858827 by vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn [127.0.0.1]
2021-02-03 13:37:23 [Pool]	[vtccoin] (Thread 5) Share rejected: {"job":"f4","ip":"127.0.0.1","worker":"vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn","difficulty":1.6161616,"error":"low difficulty share of 0.17298640706753718"}
2021-02-03 13:37:32 [Pool]	[vtccoin] (Thread 5) Share rejected: {"job":"f4","ip":"127.0.0.1","worker":"vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn","difficulty":1.6161616,"error":"low difficulty share of 0.36658791622861003"}
2021-02-03 13:37:34 [Pool]	[vtccoin] (Thread 5) Share rejected: {"job":"f4","ip":"127.0.0.1","worker":"vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn","difficulty":1.6161616,"error":"low difficulty share of 0.19020549184735405"}
2021-02-03 13:37:34 [Pool]	[vtccoin] (Thread 5) Share rejected: {"job":"f4","ip":"127.0.0.1","worker":"vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn","difficulty":1.6161616,"error":"low difficulty share of 0.444326995075419"}
2021-02-03 13:37:35 [Pool]	[vtccoin] (Thread 5) Share accepted at diff 0.44444444/0.53188842 by vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn [127.0.0.1]
2021-02-03 13:37:36 [Pool]	[vtccoin] (Thread 5) Share rejected: {"job":"f4","ip":"127.0.0.1","worker":"vtc1qgl7ku9shfdzvesh6qq44hgef8jg4zu4uc68rcn","difficulty":1.6161616,"error":"low difficulty share of 0.12848397483575263"}

When a new block is found by the network, the pool sends a work_restart and then the miner restarts its work with the new diff but not earlier.

Looks like the current job which is being worked on is simply ignoring the new difficulty which has been sent from the pool.

**Comment by CryptoGraphics** [comment]
This is how Stratum protocol works.
https://en.bitcoin.it/wiki/Stratum_mining_protocol#mining.set_difficulty
According to the specification:
mining.set_difficulty is the "next job difficulty".
Pool can send a mining.notify(new job) and the new difficulty will be applied, once the miner will switch to the new job.
mining.notify contains a `clean jobs` flag.
According to the specification:
`If true, miners should abort their current work and immediately use the new job.
If false, they can still use the current job, but should move to the new one after exhausting the current nonce range.`

Nonce is an unsigned 32 bit value so it's range equals 4294967296(0-4294967295) hashes.
Each device works with each own nonce range using an unique `extranonce` value.
GPU_0 extranonce = 0, nonce range: 0-4294967295
GPU_1 extranonce = 1, nonce range: 0-4294967295

Stratum spec was written for another algorithm(SHA256), which is much faster than Verthash and has an asic implementation.
In Verthash case: If device hash-rate is 1048576 hashes per second = ~1MH/s,
then it will take 4294967296/1048576 = 4096 sec = ~68 minutes to complete a nonce range.
In practice miner will switch to the new job only on `mining.notify(clean jobs = true).`

A potential solution to this problem will be adding a configurable timer, which will be used to poll for new jobs.

However a configurable timer is an ugly hack. Spec clearly defines a client(miner) behaviour here.
`Some pools may force a new job out when set_difficulty is sent, using clean_jobs to force the miner to begin using the new difficulty immediately.`

**Comment by steveocrypto** [comment]
I believe this is traditionally not set to true so allow the miners to finish the work they are on instead of wasting that effort.

> If false, they can still use the current job, but should move to the new one after exhausting the current nonce range.

How is this functionality implemented in other miners, using timers?

And another note - that the difficulty adjustments are typically calculated over 90 seconds to calibrate how often shares are to be received to ease server load.  An ideal range to shoot for is 1 share every 15 seconds, so if a static diff of 1 is used on a very high hasher, this results in an overload of shares (and thus vardiff re-assigns the difficulty after measuring).

I can experiment with sending a clean jobs notification with the notify in testnet this week and report back.

**Comment by stevecastaneda** [comment]
I'm not sure that the varDiff adjustments are being used even with clean_jobs set to true.

Example mining.notify being sent to a miner to verify it's set to true.

![image](https://user-images.githubusercontent.com/171488/106802540-b701b700-6628-11eb-888d-d5b52eaa7543.png)

I'm still seeing workers that should be averaging 1-3 Diff but are being assigned diffs well over 20 because the frequency of work arriving is not slowing.

I'm also not seeing the CLI that the work is being restarted, like when a block is found.  Should that be happening with clean_jobs set to true?

**Comment by steveocrypto** [comment]
I'm not sure that the varDiff adjustments are being used even with clean_jobs set to true.
Example mining.notify being sent to a miner to verify it's set to true.

![image](https://user-images.githubusercontent.com/64072/106803050-5fb01680-6629-11eb-9664-f4517d01523c.png)

I'm still seeing workers that should be averaging 1-3 Diff but are being assigned diffs well over 20 because the frequency of work arriving is not slowing.

I'm also not seeing the CLI that the work is being restarted, like when a block is found. Should that be happening with clean_jobs set to true?

**Comment by CryptoGraphics** [comment]
> How is this functionality implemented in other miners, using timers?

ccminer uses a timer with 30 seconds interval(by default).

Another possible solution:
Track both current and next difficulty from the `mining.set_difficulty`, then compare those on every `mining.notify` message which doesn't have clean_jobs = true.
- There will be no performance regressions when mining on pools with static diff and no overhead from polling.
- mining.notify(clean_jobs = false) messages with the same difficulty will still be ignored(as usual, due to big nonce range)

**Comment by steveocrypto** [comment]
I agree that that solution sounds optimal.  Happy to help test this once you have it compiled.

**Comment by ocminer** [comment]
When a difficulty update is sent the next current jobs (not NEW jobs !) are still accepted but jobs after those "old" jobs have been submitted will be rejected because the miner "knows about the new difficulty requested" - thats the way it was always.

Once the miner gets the new difficulty, the should start all subsequent jobs with this new diff and submit it accordingly. 

The method of waiting with the old diff until the nonce space is exhausted or a network block has been found is not feasible especially with coins with longer block times like 10 minutes etc. The miner would still continue to send very low diff shares and "ddos" the pool with those shares because it'd ignore the diff until a new block is found on the network.

Yes, please simply restart your worker threads once you receive a new difficulty, let them finish and submit the current work gracefully and after that let them start with the new diff and everything should be fine.

**Comment by ocminer** [comment]
Another thing I've noticed: If the pool goes down i.e. for a restart and the miner then reconnects after it's back up again - it also submits work with the old diff which it was hashing with even though the pool submitted a new initial job.

A workaround would be to simply use static diff ports for now but this won't work for performance reasons.

**Comment by CryptoGraphics** [comment]
Here is a test version(source+windows binary), which implements an idea I've mentioned in the previous post.
https://mega.nz/file/3XpSjbZS#2Pt3E3RoG6Q1wrn6cxr-V4Df6aGAWJ83xSK7dnoKxWA
Let me know if it works for you.

**Comment by steveocrypto** [comment]
Thanks!  Running tests today.  Will report back with results as soon as possible.  In the two trials I'll run tests with a very long rebroadcast, then a normal one (30 sec) to see if the miner still submits old work.

### Oberservations
(updating notes as I go)

**(clean_jobs = FALSE, jobRebroadast = 600 sec, pool difficulty = 0.1, minDiff= 0.1, varDiff Retarget every 90 sec w/ target time of a share every 15 sec)**
* When a new block is found, miner begins submitting shares at the new assigned diff setting as expected.
* When the stratum updates difficulty between the next block, miner continues to submit occasional shares at the previously set difficulty.

@CryptoGraphics Started over with testing to be safe with new observations.  
You can test the miner at `stratum+tcp://168.235.80.72:3955` (mainnet, solo payout if you happen to find a block, no fees)
This is a test server I spin up to test deployments prior to production.
I'll leave it up through Sunday evening for testing.

**Comment by ocminer** [comment]
Any chance you can push the changes into github so I can see what has actually changed ?

**Comment by CryptoGraphics** [comment]
I'll release a slightly different approach, which will allow to switch to the new job instantly.(on every mining_notify)
I need to make sure it works properly along with upcoming changes in the "WorkSize" distribution planned for 0.7.0.

**Comment by nickhoyt** [comment]
@CryptoGraphics  This is off topic for this but what are you adjusting in the worksize distribution? I noticed it was hard coded to 64 in verthash.cu this was more dynamic in cudaminer and ccminer. Also the worksize flag for gpu selection is confusing. It's not clear in the documentation that you have to include a lowercase w to make it work properly. IE 0:w1024 wWorkSize could easily be misconstrued as the name of the terminal variable making people think that it doesn't work properly.

**Comment by steveocrypto** [comment]
> I'll release a slightly different approach, which will allow to switch to the new job instantly.(on every mining_notify)
> I need to make sure it works properly along with upcoming changes in the "WorkSize" distribution planned for 0.7.0.

@CryptoGraphics Testnet is up for testing on 168.235.80.72:3950 (use a tvtc address). 

### Settings
- Vardiff retarget every 90 sec
- Share frequency target every 15 sec
- Job rebroadcasted every 1 min

**Comment by steveocrypto** [comment]
@CryptoGraphics Can I assist in any testing?  Would love to get this working soon to have the miners all working more efficiently.

**Comment by CryptoGraphics** [comment]
In v0.7.0 the miner will now instantly switch stratum jobs(on every mining.notify message).

@nickhoyt
Command line parameter validation has been improved along with updated documentation.

**Comment by steveocrypto** [comment]
> In v0.7.0 the miner will now instantly switch stratum jobs(on every mining.notify message).
> 
> @nickhoyt
> Command line parameter validation has been improved along with updated documentation.

@CryptoGraphics Amazing update, thank you!
